// Mocks generated by Mockito 5.4.4 from annotations
// in iptracker/test/features/ip_lookup/view_models/home_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:iptracker/core/result/result.dart' as _i2;
import 'package:iptracker/features/ip_lookup/models/ip_data.dart' as _i6;
import 'package:iptracker/features/ip_lookup/repository/ip_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPRepository extends _i1.Mock implements _i3.IPRepository {
  MockIPRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentServiceName => (super.noSuchMethod(
        Invocation.getter(#currentServiceName),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#currentServiceName),
        ),
      ) as String);

  @override
  List<String> get availableServiceNames => (super.noSuchMethod(
        Invocation.getter(#availableServiceNames),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i5.Future<_i2.Result<_i6.IPData>> getMyIPData() => (super.noSuchMethod(
        Invocation.method(
          #getMyIPData,
          [],
        ),
        returnValue:
            _i5.Future<_i2.Result<_i6.IPData>>.value(_FakeResult_0<_i6.IPData>(
          this,
          Invocation.method(
            #getMyIPData,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Result<_i6.IPData>>);

  @override
  _i5.Future<_i2.Result<_i6.IPData>> getIPData(String? ipAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIPData,
          [ipAddress],
        ),
        returnValue:
            _i5.Future<_i2.Result<_i6.IPData>>.value(_FakeResult_0<_i6.IPData>(
          this,
          Invocation.method(
            #getIPData,
            [ipAddress],
          ),
        )),
      ) as _i5.Future<_i2.Result<_i6.IPData>>);

  @override
  bool isValidIPAddress(String? ipAddress) => (super.noSuchMethod(
        Invocation.method(
          #isValidIPAddress,
          [ipAddress],
        ),
        returnValue: false,
      ) as bool);

  @override
  void changeService(String? serviceName) => super.noSuchMethod(
        Invocation.method(
          #changeService,
          [serviceName],
        ),
        returnValueForMissingStub: null,
      );
}
